name: AWS Role assume test
on:
  workflow_dispatch:
    inputs:
      comment:
        description: 'An optional comment'
        required: false
#permissions:
#  id-token: write
jobs:
  build:
    name: Build image
    runs-on: myRunner

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-skip-session-tagging: true
        role-to-assume: arn:aws:iam::492318887304:role/devops-action-demo
#        role-to-assume: arn:aws:iam::492318887304:role/infrapoc_devops_inframgmt_ecode
#        role-to-assume: ${{ secrets.AWS_INFRAPOC_ROLE }}
        aws-region: us-east-1
        role-session-name: GitHubActions
#        role-session-name: infrapoc-session
